### ISSUE TITLE
[BUG] Incorrect account balance calculation in non USD currencies

### ISSUE THREAD

**Issue by sudores** [ghostfolio/ghostfolio#3056] opened 2024-02-26 18:39 UTC
**Bug Description**
I've some assets added into account with non native (USD) currency (UAH being precise). Issue with that is the fact of incorrect calculation of the amount of money which are hold within those accounts. Those accounts stands only for non publicly tradable securities so they're added as `valuable` asset type into the account. 
In the `Accounts` tab it's displayed as `{total account transaction value} * {exchange rate}` (USD/UAH in my case).
In the `Portfolio/Allocations` tab it's displayed as the account value in UAH (which is incorrect already here) multiplied by rate (UAH/USD)

**To Reproduce**

1. Add some currency (e.g. UAH) in settings
2. Create account with that currency as a base currency
3. Add transaction within those account with valuable type and nominated in non-base currency (e.g. UAH)
4. Take a look at `Accounts` tabs at the account value which you've created
5. Take a look at `Portfolio/Allocations` tab as wrong calculation appears there too as too big value for platform account was assigned to.

**Expected behavior**

It's expected that account calculation would be done correctly for non-base currencies. Without saving them as USD (as it seems to me according to this)

**Screenshots**
![transaction-creature](https://github.com/ghostfolio/ghostfolio/assets/44696008/1ecc4350-4372-4a82-a4ea-cdfc0327a6dc)
Transaction creature

![activities-view](https://github.com/ghostfolio/ghostfolio/assets/44696008/161f95dd-b5c9-46d9-8622-2dbfce7100c4)
Activities view (after transaction created)

![accounts-view](https://github.com/ghostfolio/ghostfolio/assets/44696008/31b0d7f8-f6bb-4456-9b2d-7c58106769ad)
Account view (after transaction created)

![platform-view](https://github.com/ghostfolio/ghostfolio/assets/44696008/fba8f202-7790-49eb-a751-d7ec3f966f53)
Allocations view (after transaction created)

**Environment**

- Ghostfolio Version:  v2.55.0
- Cloud or Self-hosted: Self-hosted
- Experimental Features enabled or disabled: Disabled
- Browser: Mozilla Firefox 122.0
- OS: Void Linux

**Comment by dtslvr** [comment] 2024-02-26 19:16
Hi @sudores

Is this a duplicate of #3049?

**Comment by sudores** [comment] 2024-02-26 19:32
Greetings @dtslvr 
My excuses it seems to be so. I've not found it.

**Closed** 2024-02-26 19:32 UTC
Labels: question

**Comment by sudores** [comment] 2024-02-26 19:35
Duplicate
