### ISSUE TITLE
[BUG] Wrong exchange rate in activities

### ISSUE THREAD

**Issue by meuter** [ghostfolio/ghostfolio#2449] opened 2023-10-07 13:56 UTC
**Bug Description**

My main account is in EUR. But I do have some activities in USD. When displaying the details of an activities, it displays the amount of the transactions as well as the fees converted from USD to EUR. But the convertion rate used in that calculation is the current exchange rate. I believe it should be using the exchange rate at the date the transaction took place. This also affect the `Total` in the `Activities` view.

**Steps to reproduce**

1. create account in EUR
2. add some activities in USD
3. look at one activity value in USD and EUR the exchange rate to convert from USD to EUR is the current exchange rate.

**Expected behavior**

The exchange rate at the date of the tx should be used

**Screenshots**

Here's an example:

![image](https://github.com/ghostfolio/ghostfolio/assets/843867/f4432e5a-3641-4b30-8125-3b8cf49f9c31)

![image](https://github.com/ghostfolio/ghostfolio/assets/843867/b4ee59da-2a83-47df-b873-864bf8b7df09)

Note the date: Aug 20th 2021. According to `=INDEX(GOOGLEFINANCE("CURRENCY:USDEUR","price",DATE(2021,8,20)),2,2)`, the exchange rate on the date of the transaction (Aug 20th 2021) was `0.8545548`. So the EUR value should be `0.8545548 * 1360.50= 1162.621805`, not `0.9440 * 1360.50 = 1284.312` as displayed in the UI.

**Environment**

- Self-hosted
- Ghostfolio Version 2.8.0
- Browser: Chrome
- OS: Windows

**Comment by kurld** [comment] 2023-11-17 15:10
This "bug" makes Ghostfolio next to useless for everyone investing in securities where currency exchange at transaction time is involved. None of the numbers provided by Ghostfolio make sense anymore.
Please allow to select exchange rate manually for each activity.

**Comment by meuter** [comment] 2023-11-17 17:19
I would be happy with allowing to enter the exchange rate for each activity 👍

**Comment by MRobi1** [comment] 2023-12-02 19:36
> If possible please allow to select exchange rate manually for each activity and keep the rate locked for all other calculations.
> I would be happy with allowing to enter the exchange rate for each activity 👍
Manually inputting the exchange rate shouldn't be needed with the ability to pull and store historical data. Have the historical exchange rate stored, and use it to calculate the amount in USD (or whichever) on the date listed, and when displaying info, use that same historical data to convert it back into the currency of choice. Or just store the purchase details in CAD/EUR, etc.. and only use currency conversion on the current value

I believe I may be up against the same issue in #2700 but with crypto currencies.

**Comment by MRobi1** [comment] 2023-12-04 17:41
> Exchange rate should be user decision as only he knows the exact number.

I would respectfully disagree here. I have to re-input 100's of transactions due to a change in how cryptocurrency is handled, and I have absolutely no idea of the exchange rate at the time of the transaction since the transaction was done in my native currency (CAD). Currency exchange never came into play during the transaction, however I'm forced to use it in Ghostfolio.

The exchange rate used at time of entry isn't really important though. What's important is that if $1,000 CAD was invested, that it stays as $1,000 CAD. What is currently happening is that it is converting $1,000 CAD into USD using the historical exchange rate for that day and then converting it back to CAD using today's exchange rate to display. This is why $1,000 being invested is showing as $1,100 or $900 or whatever today's exchange rate happens to make it. It's incorrect accounting and a fundamental flaw in how ghostfolio handles currency exchange. The dev has opened a crowdfunding link and will fix it once it raises $100 USD. 

What have you switched over to? I'd like to check it out myself.

**Comment by underwater** [comment] 2023-12-04 18:04
Hello, let me add my 2 cents here...
I think the confusion is that we are discussing profit and loss reporting in a 'reporting currency' for assets held in the portfolio which are denominated in another (asset currency).

The divergence is opinions can be summarized perhaps as at the detail of how reporting is handling gains and losses and allocating that across both to asset price fluctuations as well as fx rate changes.   

Ideally I think we would agree that we would have to be able to seperately report on each of these and distinguish in our P/L calculations those arising from 

- Price P/L --> gain / loss due to price changes (CurrentPrice - PurchasePrice)  --> this amount would specified in asset currency would represent only gain / loss due to the price level of the investment in its own currency.

- Currency P/L --> Gain / loss due to fx rate changes fluctuations (CurrentFXRate - PurchaseFxRate) --> of the currency in which the asset is denominated against the client reporting currency since the asset was purchased.

does that make sense ?



- gain / loss due to

**Comment by MRobi1** [comment] 2023-12-04 18:19
There is no scenario in P/L reporting where the initial amount invested changes. This is the issue at hand. A $1,000 CAD investment is being reported as $900, $1,100 or anywhere the exchange rate happens to be at on the day you're looking at it. $1,000 invested NEEDS to stay as $1,000 invested. 

Even if I were to make an investment in USD and have that investment shown in ghostfolio in CAD, the amount invested needs to stay true to the exchange rate on the day I made that investment. Because as you said, we are now dealing with both Price and currency P/L. You can have an asset that's completely flat at 0% and gain/lose due to fx fluctuation. However through all of that my initial investment never changes, but ghostfolio is saying it did.

**Comment by MatanRubin** [comment] 2023-12-11 19:35
I'm having the same issue, and I would add that Ghostfolio should store the original currency. It seems like currently when I enter an activity in some foreign currency Ghostfolio immediately converts it to USD and forgets the original currency. When I open the activity again I see it as if it was purchased in USD, although it was purchased in ILS.

**Comment by dtslvr** [comment] 2023-12-12 07:51
> It seems like currently when I enter an activity in some foreign currency Ghostfolio immediately converts it to USD and forgets the original currency.

I can confirm this.

> I would add that Ghostfolio should store the original currency.

That sounds like a concrete proposal, @MatanRubin. We could optionally store the currency which overrides the original currency from the asset profile. Would you like to take a closer look and figure out an implementation?

**Comment by tiptr** [comment] 2023-12-17 21:24
+1 here. As someone with EUR as main currency but having e.g. ETFs based on USD, the currency conversion is messing up the EUR values of the original investment (and therefore also e.g. the performance).

I guess the minimum required fix is to use the exchange rate of the historic day back from USD to EUR when displaying the original investment and everything building upon that.

Preferably, we should store the original EUR investment instead of only a converted USD value and also display that e.g. in the activities overview instead or in addition to the ETF currency.

**Comment by MRobi1** [comment] 2024-02-11 17:12
@dtslvr has there been any further consideration on this?
 
As it stands, Ghostfolio can only be used as a single currency portfolio tracker. As soon as currency conversion comes into play, seemingly regardless of which currency it is, it does not present the data accurately. I'm sure there are countless users who's data is being misrepresented without them even knowing.

**Comment by dtslvr** [comment] 2024-02-25 10:41
Resolved via https://github.com/ghostfolio/ghostfolio/pull/3039.

**Closed by dtslvr** 2024-02-25 10:41 UTC

**Comment by MRobi1** [comment] 2024-02-25 16:12
> Resolved via #3039.

Still unresolved

As seen here, 10 shares @ $100 CAD = $1,000 CAD as an initial investment
![image](https://github.com/ghostfolio/ghostfolio/assets/34860474/19415c18-4834-4b2d-aa2a-c8335ebeed77)

After saving it is showing the same investment as $1,018 CAD
![image](https://github.com/ghostfolio/ghostfolio/assets/34860474/3cdf507a-4b6d-4c22-b33b-1b76e1473921)

It appears it is converting the initial activity to USD using historical exchange rate (which is good) and then in performance calculation it is converting that initial activity back to CAD using today's exchange rate (which is not good). Everything historical needs to be calculated using the historical exchange rate at the time of transaction and then kept that way. Only the current market price should be converted using today's exchange rate. Basically it is creating a currency hedged transaction when it should be unhedged.

I think the simplest way to do this would be to store the historical activities in whatever currency the user selects when inputting the activity. This way for performance calculation the only thing with currency conversion would be the current market data.
