### ISSUE TITLE
[BUG] Cannot add any symbol other than crypto

### ISSUE THREAD

**Issue by nodiaque** [ghostfolio/ghostfolio#3284] opened 2024-04-17 12:13 UTC
**Bug Description**

In activity tab, when I enter a symbol, only Cryptocurrency are showed
![image](https://github.com/ghostfolio/ghostfolio/assets/324425/0ea016ad-a5e4-4cd1-a24f-4ff2e45cd5ec)
![image](https://github.com/ghostfolio/ghostfolio/assets/324425/0842888e-d435-4156-8ef3-ac197b1f2f5e)

**To Reproduce**

1. Go into activity
2. Click Add
3. Enter a symbol

**Expected behavior**

Show all symbol, not just crypto

**Logs**

> 
> [Nest] 288  - 04/17/2024, 12:12:31 PM    WARN [YahooFinanceService] Fallback to yahooFinance.quoteSummary()
> [Nest] 288  - 04/17/2024, 12:12:31 PM   ERROR [YahooFinanceService] Could not get quote summary for AMD
> [Nest] 288  - 04/17/2024, 12:12:31 PM   ERROR [YahooFinanceService] Could not get quote summary for ACB.TO
> [Nest] 288  - 04/17/2024, 12:12:31 PM   ERROR [YahooFinanceService] Could not get quote summary for AC.TO
> [Nest] 288  - 04/17/2024, 12:12:31 PM   ERROR [YahooFinanceService] Could not get quote summary for ABT
> [Nest] 288  - 04/17/2024, 12:12:31 PM   ERROR [YahooFinanceService] Could not get quote summary for BA
> [Nest] 288  - 04/17/2024, 12:12:31 PM   ERROR [YahooFinanceService] Could not get quote summary for CGX.TO
> [Nest] 288  - 04/17/2024, 12:12:31 PM   ERROR [YahooFinanceService] Could not get quote summary for INTC
> [Nest] 288  - 04/17/2024, 12:12:31 PM   ERROR [YahooFinanceService] Could not get quote summary for IWF
> [Nest] 288  - 04/17/2024, 12:12:31 PM   ERROR [YahooFinanceService] Could not get quote summary for COST
> [Nest] 288  - 04/17/2024, 12:12:31 PM   ERROR [YahooFinanceService] Could not get quote summary for MRNA
> [Nest] 288  - 04/17/2024, 12:12:31 PM   ERROR [YahooFinanceService] Could not get quote summary for MSFT
> [Nest] 288  - 04/17/2024, 12:12:31 PM   ERROR [YahooFinanceService] Could not get quote summary for NA.TO
> [Nest] 288  - 04/17/2024, 12:12:31 PM   ERROR [YahooFinanceService] Could not get quote summary for PFE
> [Nest] 288  - 04/17/2024, 12:12:31 PM   ERROR [YahooFinanceService] Could not get quote summary for SPY
> [Nest] 288  - 04/17/2024, 12:12:31 PM   ERROR [YahooFinanceService] Could not get quote summary for TSLA
> [Nest] 288  - 04/17/2024, 12:12:31 PM   ERROR [YahooFinanceService] Could not get quote summary for VFV.TO
> [Nest] 288  - 04/17/2024, 12:12:31 PM   ERROR [YahooFinanceService] Could not get quote summary for VDY.TO
> [Nest] 288  - 04/17/2024, 12:12:31 PM   ERROR [YahooFinanceService] Could not get quote summary for VTV
> [Nest] 288  - 04/17/2024, 12:12:38 PM   ERROR [YahooFinanceService] Error: Invalid Crumb. For Developers - https://bit.ly/yahoo-finance-api-feedback

**Environment**

- Ghostfolio Version 2.72.0
- Self-hosted
- Experimental Features disabled
- Browser: Edge / Firefox
- OS: Unraid

**Comment by dtslvr** [comment] 2024-04-17 12:29
Duplicate of https://github.com/ghostfolio/ghostfolio/issues/3276.

**Closed by dtslvr** 2024-04-17 12:29 UTC
