### ISSUE TITLE
Extend asset profile for currency

### ISSUE THREAD

**Issue by dtslvr** [ghostfolio/ghostfolio#3488] opened 2024-06-12 18:46 UTC
As a follow-up to https://github.com/ghostfolio/ghostfolio/issues/3006, add the missing attributes for currencies (e.g. `USDEUR`) to market data endpoint `api/v1/admin/market-data/:dataSource/:symbol`:

* `activitiesCount`
* `dataSource`
* `dateOfFirstActivity`

<img width="1008" alt="asset-profile-usdeur" src="https://github.com/ghostfolio/ghostfolio/assets/4159106/53610819-f395-417b-82a4-a4f4326d3b95">

**Comment by dtslvr** [comment] 2024-06-12 18:47
Are you interested in taking on this issue, @SirZemar?

**Comment by SirZemar** [comment] 2024-06-13 10:03
Hey @dtslvr. Yes, assign it  to me 😃. Can you give me more detail when are these attributes missing. I wasn't able to reproduce what you show in the image.
![issue#3488](https://github.com/ghostfolio/ghostfolio/assets/87383586/dc45328f-4c9b-4f5f-8789-564dd8bbe021)

**Comment by SirZemar** [comment] 2024-06-13 19:50
Alright! There are a few things to consider, @dtslvr.

Our endpoints returns an assetProfile with partial type of EnhancedSymbolProfile. 

```js
      assetProfile: assetProfile ?? {
        symbol,
        currency: '-'
      }
```

We can now pass the dataSource, which was missing, and a value of 0 for activitiesCount.
```js
      assetProfile: assetProfile ?? {
        dataSource,
        symbol,
        currency: '-',
        activitiesCount = 0,
      }
```

As for `dateOfFirstActivity`  we should keep its Date type. So in this case, since its an optional field, should be undefined and let our template deal with its conditional nature.

I notice also that the component `gf-admin-market-data-detail` is expecting to get a `dateOfFirstActivity` attribute of type string instead of Date. Something worth to look into.

**Comment by dtslvr** [comment] 2024-06-14 07:54
For `activitiesCount` and `dateOfFirstActivity`, it should reuse the logic from https://github.com/ghostfolio/ghostfolio/issues/3006 (instead of `activitiesCount: 0` / `dateOfFirstActivity: undefined`).

You can use

```
isCurrency(
  symbol.substring(0, symbol.length - DEFAULT_CURRENCY.length)
)
```

to check if a `symbol` is actually a currency like `USDEUR`.

**Comment by SirZemar** [comment] 2024-06-14 11:59
I haven't checked your refactoring 53c1379b543e2cd147c4b3459604e13333da173b (#3006) until now. 

I am a bit confused how we are suppose to track the activities for currencies. I thought for symbol, for example 'USDEUR' , we needed to find all orders where only both currencies were included: order.currency: 'USD', symbolProfile.currency: 'EUR', but i seems we count all symbolProfile.currency regardless the order.currency.

I will replicate the same logic from #3006 to this one, although I don't fully understand it 😅

**Closed** 2024-06-22 07:54 UTC
Labels: enhancement, good first issue, help wanted
