### ISSUE TITLE
[BUG] Dividends in different currency than asset 

### ISSUE THREAD

**Issue by patrick7** [ghostfolio/ghostfolio#1712] opened 2023-02-16 22:07 UTC
It's not possible to create a dividend payout in a different currency than the asset is.

e.g. I buy ETFs at SIX Switzerland in CHF, but the dividend is paid out in USD. There's no possibility to change the dividend's currency (while it is possible for the fee-field)

**Comment by dtslvr** [comment] 2023-02-17 10:17
Duplicate of #705.

**Closed by dtslvr** 2023-02-17 10:17 UTC
