### ISSUE TITLE
Error when saving manual data in Market Data section

### ISSUE THREAD

**Issue by hoangpla8** [ghostfolio/ghostfolio#3298] opened 2024-04-19 07:02 UTC
### Issue
When performing operations such as adding, editing, and saving manual data in the Market Data section of the application, no action is taken and no specific error message is displayed. However, in the browser console, I receive an error like the following:

### Steps to Reproduce
1. Open the Ghostfolio application.
2. Access the Market Data section.
3. Perform operations such as adding, editing, and saving manual data.
4. Check the results and error in the browser console.

### Expected Behavior
When I perform operations such as adding, editing, and saving manual data in the Market Data section, I expect the system to process and save the data accurately.

### Environment
- Operating System: [Windows]
- Browser: [Chrome]
- Ghostfolio Version: [2.73.0]

![Screenshot 2024-04-19 140321](https://github.com/ghostfolio/ghostfolio/assets/41339977/140ff5ea-da07-4106-996a-21e6e8387510)

**Comment by gstr3745** [comment] 2024-04-19 13:23
I'm experiencing a similar problem with non manual entries: I got the same 400 error trying to add notes or to edit a field and a 500 error trying to delete it, which throws an exception as shown in the following log.

**Logs**
_Deleting an entry_
```
[Nest] 111  - 04/19/2024, 12:10:31 PM   ERROR [ExceptionsHandler]
Invalid `prisma.symbolProfile.delete()` invocation:


Foreign key constraint failed on the field: `SymbolProfileOverrides_symbolProfileId_fkey (index)`
PrismaClientKnownRequestError:
Invalid `prisma.symbolProfile.delete()` invocation:


Foreign key constraint failed on the field: `SymbolProfileOverrides_symbolProfileId_fkey (index)`
    at In.handleRequestError (/ghostfolio/apps/api/node_modules/@prisma/client/runtime/library.js:122:6854)
    at In.handleAndLogRequestError (/ghostfolio/apps/api/node_modules/@prisma/client/runtime/library.js:122:6188)
    at In.request (/ghostfolio/apps/api/node_modules/@prisma/client/runtime/library.js:122:5896)
    at async l (/ghostfolio/apps/api/node_modules/@prisma/client/runtime/library.js:127:11167)
    at async AdminService.deleteProfileData (/ghostfolio/apps/api/main.js:1:432774)
    at async /ghostfolio/apps/api/node_modules/@nestjs/core/router/router-execution-context.js:46:28
    at async /ghostfolio/apps/api/node_modules/@nestjs/core/router/router-proxy.js:9:17
    at async /ghostfolio/apps/api/node_modules/@nestjs/core/router/router-explorer.js:176:17
```

**Environment**
- Ghostfolio Version 2.73.0
- Self-hosted
- Experimental Features enabled disabled
- Browser: Chrome
- OS: Windows

**Comment by karter16** [comment] 2024-04-20 02:14
I believe this is a duplicate of #3265

**Comment by karter16** [comment] 2024-04-24 06:08
This is caused by #3218. It is possible to save change successfully ONLY if the URL field is populated with a url beginning with "https". Any other scenario (including saving an existing record that has url = null) results in the behaviour described.

**Comment by dtslvr** [comment] 2024-04-24 19:16
Closed as duplicate of https://github.com/ghostfolio/ghostfolio/issues/3265.

**Closed by dtslvr** 2024-04-24 19:16 UTC
