### ISSUE TITLE
[BUG] Stock picker on activities not working in Safari

### ISSUE THREAD

**Issue by cbirkenbeul** [ghostfolio/ghostfolio#1827] opened 2023-04-05 20:16 UTC
Hi,

if I put in a ISIN or WKN in the corresponding field in the activity tab the picker does not work on Safari. The clickable field applies but it's not clickable. It's working on chrome on macOS, so I have a workaround.

The issue appears on one of the last 3 versions. I just realized it today. 

I'm running 1.250.0
<img width="909" alt="Bildschirm­foto 2023-04-05 um 22 17 16" src="https://user-images.githubusercontent.com/1380162/230200073-de33491d-dcc8-4214-bdd7-3e066a08a489.png">

**Comment by dtslvr** [comment] 2023-04-07 08:36
Safari is throwing the following error:

`TypeError: undefined is not an object (evaluating 'this.autocomplete.options.changes')`

**Comment by karter16** [comment] 2024-04-24 08:11
@dtslvr Just trying to help with tidy up where I can - have tested this today and I cannot reproduce this bug.

Ghostfolio Version: 2.73
Self Hosted
Browser: Safari 17.1
OS: MacOS 14.1.1

Using the example given in the initial bug report I searched on the ISIN

<img width="892" alt="Screenshot 2024-04-24 at 8 08 52 PM" src="https://github.com/ghostfolio/ghostfolio/assets/4284373/2e43c55c-2fc5-41f5-a19f-7927169d9f69">

Result is shown and is clickable resulting in:
<img width="869" alt="Screenshot 2024-04-24 at 8 08 27 PM" src="https://github.com/ghostfolio/ghostfolio/assets/4284373/d20d642e-a11a-4405-adbd-0dfe80ef6fa7">

I would suggest that this can be closed as no longer reproducible.

**Closed** 2024-04-24 09:47 UTC
Labels: bug, help wanted
