### ISSUE TITLE
[BUG] Unable to see activity when experimental features are turned on

### ISSUE THREAD

**Issue by Avendo07** [ghostfolio/ghostfolio#2907] opened 2024-01-22 10:20 UTC
**Bug Description**
With Experimental features turned on, unable to see new activities in activity tab(if no activity is already added)

**To Reproduce**

1. Start with 0 activities added
2. Turn on experimental features
3. Add a new activity

**Expected behavior**

It should add a new activity, and show in the activity tab.

**Screenshots**

It shows no activity, but the activities are being added as can be checked in the holdings and the accounts tab.

**Environment**

- Ghostfolio Version 2.41.0
- Self-hosted
- Experimental Features enabled
- Browser - firefox
- OS - for browser(mac), for container (linux)

**Comment by dtslvr** [comment] 2024-02-04 14:48
Hi @Avendo07

We were unable to reproduce the issue described here with the current codebase. We're closing this issue now.
If you encounter this problem again with no active filter, please open a new issue with detailed steps to reproduce.

**Closed by dtslvr** 2024-02-04 14:48 UTC

**Comment by toffee** [comment] 2024-04-18 19:35
With 2.73.0 the described behavior is still reproducible in my self hosted environment. With default logging nothing is printed to log.
I'm able to see activities if I turn off the Experimental features.
With Experimental features on the "Add activity" popup is displayed and an empty table.
