### ISSUE TITLE
[BUG] Unable to delete symbol in Market Data

### ISSUE THREAD

**Issue by VibeNL** [ghostfolio/ghostfolio#3440] opened 2024-05-30 12:08 UTC
**Important Notice**

The issue tracker is **ONLY** used for reporting bugs. New features should be discussed in our [Slack](https://join.slack.com/t/ghostfolio/shared_invite/zt-vsaan64h-F_I0fEo5M0P88lP9ibCxFg) community or in [Discussions](https://github.com/ghostfolio/ghostfolio/discussions).

Incomplete or non-reproducible issues may be closed, but we are here to help! If you encounter difficulties reproducing the bug or need assistance, please reach out to our community channels mentioned above.

Thank you for your understanding and cooperation!

**Bug Description**
When trying to delete a symbol, I get a HTTP 500

**To Reproduce**

1. Go to market data
2. Delete a symbol

**Expected behavior**

Symbol is deleted

**Logs**

Invalid `prisma.symbolProfile.delete()` invocation: 
Foreign key constraint failed on the field: `SymbolProfileOverrides_symbolProfileId_fkey (index)`
PrismaClientKnownRequestError: 
Invalid `prisma.symbolProfile.delete()` invocation:
Foreign key constraint failed on the field: `SymbolProfileOverrides_symbolProfileId_fkey (index)`
    at In.handleRequestError ([/ghostfolio/apps/api/node_modules/@prisma/client/runtime/library.js:122:6854](mailto:/ghostfolio/apps/api/node_modules/@prisma/client/runtime/library.js:122:6854))
    at In.handleAndLogRequestError ([/ghostfolio/apps/api/node_modules/@prisma/client/runtime/library.js:122:6188](mailto:/ghostfolio/apps/api/node_modules/@prisma/client/runtime/library.js:122:6188))
    at In.request ([/ghostfolio/apps/api/node_modules/@prisma/client/runtime/library.js:122:5896](mailto:/ghostfolio/apps/api/node_modules/@prisma/client/runtime/library.js:122:5896))
    at async l ([/ghostfolio/apps/api/node_modules/@prisma/client/runtime/library.js:127:11167](mailto:/ghostfolio/apps/api/node_modules/@prisma/client/runtime/library.js:127:11167))
    at async AdminService.deleteProfileData (/ghostfolio/apps/api/main.js:1:498924)
    at async [/ghostfolio/apps/api/node_modules/@nestjs/core/router/router-execution-context.js:46:28](mailto:/ghostfolio/apps/api/node_modules/@nestjs/core/router/router-execution-context.js:46:28)
    at async [/ghostfolio/apps/api/node_modules/@nestjs/core/router/router-proxy.js:9:17](mailto:/ghostfolio/apps/api/node_modules/@nestjs/core/router/router-proxy.js:9:17)
    at async [/ghostfolio/apps/api/node_modules/@nestjs/core/router/router-explorer.js:176:17](mailto:/ghostfolio/apps/api/node_modules/@nestjs/core/router/router-explorer.js:176:17)

**Environment**

- Ghostfolio Version 2.82.0
- Self-hosted
- Experimental Features disabled
- Edge latest
- Windows

**Comment by dtslvr** [comment] 2024-05-30 12:12
This seems to be a duplicate of https://github.com/ghostfolio/ghostfolio/issues/3349 and https://github.com/ghostfolio/ghostfolio/issues/3435.

**Closed by dtslvr** 2024-05-30 12:12 UTC
