### ISSUE TITLE
Daily data indicator control on the Market Data > Symbol screen does not display month if there are no data points for that month

### ISSUE THREAD

**Issue by karter16** [ghostfolio/ghostfolio#2539] opened 2023-10-24 07:36 UTC
**Bug Description**

On the Admin Control > Market Data > Symbol screen under the historical price graph is a control/section that list out past months and shows a red/green square for each day of that month depending on whether historical price data is populated for that day or not.

I am unsure whether it is by design or not, but if there are no data points for a given month, the entire month is missing from that control/list of past months. It makes sense that you wouldn't show months earlier than the first data point you have, but if the month/s that are missing are in the middle of your data set it's easy to miss that you have missing data for the month. 

**To Reproduce**

1. Create a manual source and populate at least one data point for a month some time ago. (or use an automated source with an entire missing month of data)
2. Populate a data point from today/yesterday.
3. Observe that intermediary months are missing entirely from the control

**Expected behavior**
My suggestion would be that the behaviour should be that any month with no data points, where the month is after the oldest data point you do have, should be displayed in the list (with every day marked in red).

**Screenshots**

<img width="791" alt="Screenshot 2023-10-24 at 8 26 51 PM" src="https://github.com/ghostfolio/ghostfolio/assets/4284373/a8306ac9-f2bb-48c0-8918-e3843ef2b800">

**Logs**

**Environment**

- Self-hosted
- Ghostfolio Version 2.14.0
- Browser Safari Version 17.0 (19616.1.27.211.1)
- OS MacOS Sonoma

**Additional context**

**Comment by nipun005** [comment] 2023-10-25 09:26
Hi @karter16, Can you please help to replicate this issue. I am using Ghostfolio website first time, so not sure about all the options.
Currently I am on this main page- https://ghostfol.io/en/home/market

Now how to replicate this issue further

**Comment by dtslvr** [comment] 2023-10-25 09:30
> Now how to replicate this issue further

@nipun005 this is only available for administrators (either development or self-hosting)

**Comment by LIYANMUBARAK** [comment] 2023-10-26 03:40
@dtslvr  Can you please assign this to me?

**Comment by dtslvr** [comment] 2023-11-12 18:26
What is the current status here, @LIYANMUBARAK?

**Comment by LIYANMUBARAK** [comment] 2023-11-14 04:12
Hi **@dtslvr** ,
There is an error I am facing while running the application,if the issue is urgent you can assign it to someone else.

**Comment by dtslvr** [comment] 2024-03-29 15:56
> I'm assuming this is still open?

Yes, I think it has not been fixed yet.

**Closed** 2024-03-30 07:50 UTC
Labels: bug, good first issue, help wanted, self-hosted, hacktoberfest
