### ISSUE TITLE
Disable Account Creation

### ISSUE THREAD

**Issue by rldaugherty** [ghostfolio/ghostfolio#1400] opened 2022-10-27 16:31 UTC
Not a "must have", but something that's a QOL bonus would be to give the admin the ability to hide the "Get Started" buttons on the homepage for the self-hosted versions. A toggle that would apply a CSS rule might be the most time efficient way to achieve this. This would simply restrict other, unknown users from possibly trying to access the DB through nefarious means.

**Comment by dtslvr** [comment] 2022-10-27 17:24
Duplicate of #970.

**Closed by dtslvr** 2022-10-27 17:24 UTC
Labels: self-hosted
