### ISSUE TITLE
Dividends do not count into the cash balance of an account. Where do they go?

### ISSUE THREAD

**Issue by Resurrectum** [ghostfolio/ghostfolio#1903] opened 2023-04-28 20:12 UTC
When I enter a `dividend` action, the value does not add up to the cash balance of the account. It actually goes nowhere it seems. Am I missing something?

**Comment by dtslvr** [comment] 2023-04-30 07:40
Duplicate of #1867.

**Closed by dtslvr** 2023-04-30 07:40 UTC
