### ISSUE TITLE
Automatic currency conversion for unit price

### ISSUE THREAD

**Issue by Ysujy** [ghostfolio/ghostfolio#1731] opened 2023-02-19 17:15 UTC
Many European Brokers automatically convert securities usually traded in USD to EUR, which makes manually importing them accurately next to impossible. These Brokers typically use the foreign exchange buying rate with minimal margins, meaning converting the EUR/USD exchange rate for the buying date would probably be sufficiently accurate.

The current system makes it next to impossible for certain users to use Ghostfolio efficiently.

**Comment by dtslvr** [comment] 2023-02-19 17:26
Duplicate of #705.

**Closed by dtslvr** 2023-02-19 17:26 UTC
