### ISSUE TITLE
[BUG] Neither apiKey nor config.authenticator provided

### ISSUE THREAD

**Issue by nitobuendia** [ghostfolio/ghostfolio#4042] opened 2024-11-12 23:56 UTC
**Bug Description**

Container fails to initialize with `Error: Neither apiKey nor config.authenticator provided`

**To Reproduce**

Just initialize the container: `docker-compose up`. More details (logs) later.

**Expected behavior**

Container initializes.

**Logs**

```
ghostfolio    | + echo Running database migrations
ghostfolio    | + npx prisma migrate deploy
ghostfolio    | Running database migrations
ghostfolio    | Prisma schema loaded from prisma/schema.prisma
ghostfolio    | Datasource "db": PostgreSQL database "ghostfolio", schema "public" at "<redacted-url>"
ghostfolio    |
ghostfolio    | 91 migrations found in prisma/migrations
ghostfolio    |
ghostfolio    |
ghostfolio    | No pending migrations to apply.
ghostfolio    | npm notice
ghostfolio    | npm notice New minor version of npm available! 10.8.2 -> 10.9.0
ghostfolio    | npm notice Changelog: https://github.com/npm/cli/releases/tag/v10.9.0
ghostfolio    | npm notice To update run: npm install -g npm@10.9.0
ghostfolio    | npm notice
ghostfolio    | + echo Seeding the database
ghostfolio    | + npx prisma db seed
ghostfolio    | Seeding the database
ghostfolio    | Running seed command `node prisma/seed.js` ...
ghostfolio    |
ghostfolio    | 🌱  The seed command has been executed.
ghostfolio    | ┌─────────────────────────────────────────────────────────┐
ghostfolio    | │  Update available 5.21.1 -> 5.22.0                      │
ghostfolio    | │  Run the following to update                            │
ghostfolio    | │    npm i --save-dev prisma@latest                       │
ghostfolio    | │    npm i @prisma/client@latest                          │
ghostfolio    | └─────────────────────────────────────────────────────────┘
ghostfolio    | Starting the server
ghostfolio    | + echo Starting the server
ghostfolio    | + node main
ghostfolio    | [Nest] 233  - 11/12/2024, 11:42:12 PM     LOG [NestFactory] Starting Nest application...
ghostfolio    | [Nest] 233  - 11/12/2024, 11:42:12 PM     LOG [InstanceLoader] ApiModule dependencies initialized +39ms
ghostfolio    | [Nest] 233  - 11/12/2024, 11:42:12 PM     LOG [InstanceLoader] ConfigurationModule dependencies initialized +0ms
ghostfolio    | [Nest] 233  - 11/12/2024, 11:42:12 PM     LOG [InstanceLoader] CryptocurrencyModule dependencies initialized +0ms
ghostfolio    | [Nest] 233  - 11/12/2024, 11:42:12 PM     LOG [InstanceLoader] TransformDataSourceInRequestModule dependencies initialized +0ms
ghostfolio    | [Nest] 233  - 11/12/2024, 11:42:12 PM     LOG [InstanceLoader] TransformDataSourceInResponseModule dependencies initialized +0ms
ghostfolio    | [Nest] 233  - 11/12/2024, 11:42:12 PM     LOG [InstanceLoader] RedactValuesInResponseModule dependencies initialized +0ms
ghostfolio    | [Nest] 233  - 11/12/2024, 11:42:12 PM     LOG [InstanceLoader] BullModule dependencies initialized +0ms
ghostfolio    | [Nest] 233  - 11/12/2024, 11:42:12 PM     LOG [InstanceLoader] JwtModule dependencies initialized +2ms
ghostfolio    | [Nest] 233  - 11/12/2024, 11:42:12 PM     LOG [InstanceLoader] JwtModule dependencies initialized +0ms
ghostfolio    | [Nest] 233  - 11/12/2024, 11:42:12 PM     LOG [InstanceLoader] DiscoveryModule dependencies initialized +1ms
ghostfolio    | [Nest] 233  - 11/12/2024, 11:42:12 PM     LOG [InstanceLoader] PerformanceLoggingModule dependencies initialized +0ms
ghostfolio    | [Nest] 233  - 11/12/2024, 11:42:12 PM     LOG [InstanceLoader] ConfigHostModule dependencies initialized +0ms
ghostfolio    | [Nest] 233  - 11/12/2024, 11:42:12 PM     LOG [InstanceLoader] SitemapModule dependencies initialized +15ms
ghostfolio    | [Nest] 233  - 11/12/2024, 11:42:12 PM     LOG [InstanceLoader] ServeStaticModule dependencies initialized +4ms
ghostfolio    | [Nest] 233  - 11/12/2024, 11:42:12 PM     LOG [InstanceLoader] BullModule dependencies initialized +0ms
ghostfolio    | [Nest] 233  - 11/12/2024, 11:42:12 PM     LOG [InstanceLoader] EventEmitterModule dependencies initialized +0ms
ghostfolio    | [Nest] 233  - 11/12/2024, 11:42:12 PM     LOG [InstanceLoader] ScheduleModule dependencies initialized +0ms
ghostfolio    | [Nest] 233  - 11/12/2024, 11:42:12 PM     LOG [InstanceLoader] ConfigModule dependencies initialized +0ms
ghostfolio    | [Nest] 233  - 11/12/2024, 11:42:12 PM     LOG [InstanceLoader] PrismaModule dependencies initialized +1ms
ghostfolio    | [Nest] 233  - 11/12/2024, 11:42:12 PM     LOG [InstanceLoader] BullModule dependencies initialized +0ms
ghostfolio    | [Nest] 233  - 11/12/2024, 11:42:12 PM     LOG [InstanceLoader] BullModule dependencies initialized +0ms
ghostfolio    | [Nest] 233  - 11/12/2024, 11:42:12 PM     LOG [InstanceLoader] DataEnhancerModule dependencies initialized +0ms
ghostfolio    | [Nest] 233  - 11/12/2024, 11:42:12 PM     LOG [InstanceLoader] PropertyModule dependencies initialized +1ms
ghostfolio    | [Nest] 233  - 11/12/2024, 11:42:12 PM     LOG [InstanceLoader] SymbolProfileModule dependencies initialized +0ms
ghostfolio    | [Nest] 233  - 11/12/2024, 11:42:12 PM     LOG [InstanceLoader] ImpersonationModule dependencies initialized +0ms
ghostfolio    | [Nest] 233  - 11/12/2024, 11:42:12 PM     LOG [InstanceLoader] TagModule dependencies initialized +0ms
ghostfolio    | [Nest] 233  - 11/12/2024, 11:42:12 PM     LOG [InstanceLoader] MarketDataModule dependencies initialized +0ms
ghostfolio    | [Nest] 233  - 11/12/2024, 11:42:12 PM   ERROR [ExceptionHandler] Neither apiKey nor config.authenticator provided
ghostfolio    | Error: Neither apiKey nor config.authenticator provided
ghostfolio    |     at Stripe._setAuthenticator (/ghostfolio/apps/api/node_modules/stripe/cjs/stripe.core.js:166:23)
ghostfolio    |     at new Stripe (/ghostfolio/apps/api/node_modules/stripe/cjs/stripe.core.js:102:14)
ghostfolio    |     at new SubscriptionService (/ghostfolio/apps/api/main.js:1:76274)
ghostfolio    |     at Injector.instantiateClass (/ghostfolio/apps/api/node_modules/@nestjs/core/injector/injector.js:365:19)
ghostfolio    |     at callback (/ghostfolio/apps/api/node_modules/@nestjs/core/injector/injector.js:65:45)
ghostfolio    |     at async Injector.resolveConstructorParams (/ghostfolio/apps/api/node_modules/@nestjs/core/injector/injector.js:144:24)
ghostfolio    |     at async Injector.loadInstance (/ghostfolio/apps/api/node_modules/@nestjs/core/injector/injector.js:70:13)
ghostfolio    |     at async Injector.loadProvider (/ghostfolio/apps/api/node_modules/@nestjs/core/injector/injector.js:97:9)
ghostfolio    |     at async /ghostfolio/apps/api/node_modules/@nestjs/core/injector/instance-loader.js:56:13
ghostfolio    |     at async Promise.all (index 3)
```

**Environment**

- Ghostfolio Version: Latest (`ghostfolio/ghostfolio:latest`) - which I assume is `2.122.0`
- Self-hosted
- Experimental Features disabled
- Browser: Chrome Version 130.0.6723.92 (Official Build) (x86_64) - but irrelevant as it's server-side
- OS: Ubuntu 22.04.5 LTS - but running on a container.

docker-compose.yaml

```
services:
  ghostfolio:
    image: ghostfolio/ghostfolio:latest
    container_name: ghostfolio
    restart: unless-stopped
    env_file:
      - secrets.env
    labels:
      - "traefik.enable=true"
      - <traefik-labels>
```

secrets.env

```
COMPOSE_PROJECT_NAME=ghostfolio

# CACHE
REDIS_HOST=<redacted>
REDIS_PORT=<redacted>
REDIS_PASSWORD="<redacted>"

# POSTGRES
POSTGRES_DB=<redacted>
POSTGRES_USER=<redacted>
POSTGRES_PASSWORD="<redacted>"
DATABASE_URL="<redacted>"

# GHOSTFOLIO
NODE_ENV=production

# API KEYS
ACCESS_TOKEN_SALT="<redacted>"
ALPHA_VANTAGE_API_KEY=""  # Empty
JWT_SECRET_KEY="<redacted>"
```

**Additional context**

I had Ghostfolio running for a long time. This started happening recently, but I don't know when exactly.

Seems related to [this bug](https://github.com/stripe/stripe-node/issues/2207).

**Comment by dtslvr** [comment] 2024-11-13 06:19
Hi @nitobuendia

This bug was present in 2.121.0 and has been fixed in 2.121.1. Please upgrade your instance.

By the way you can check the version you are currently running in the _Admin Control_ panel.

**Closed by dtslvr** 2024-11-13 06:19 UTC

**Comment by dtslvr** [comment] 2024-11-13 06:42
Duplicate of https://github.com/ghostfolio/ghostfolio/issues/4018.

**Comment by nitobuendia** [comment] 2024-11-13 23:50
Thanks a lot, @dtslvr - I can confirm that updating (repulling the image) worked.

As for the checking the version on the Admin Control panel, it's hard when the app is crashing before initializing - otherwise I would have provided it. Without the container starting, and on tag latest, perhaps the sha of the image would have been the best way to compare.

**Comment by dtslvr** [comment] 2024-11-14 07:50
> As for the checking the version on the Admin Control panel, it's hard when the app is crashing before initializing

Good point 🤓
