### ISSUE TITLE
[BUG] Total investment value not correct

### ISSUE THREAD

**Issue by BloodBlender** [ghostfolio/ghostfolio#4083] opened 2024-11-30 11:34 UTC
**Bug Description**

Total investment value and total amount not calculating correctly on the graph with multiple currency. In the overview the value is correct but in the graph is not. Currently the base currency and others are just added together and displayed in the graph.

**To Reproduce**

1. add multiple currency's 
2. add assets
3. look at the graph

**Expected behavior**

Currency different than base should be calculated to base currency and displayed int the graph.

**Screenshots**
![iuaesghfuoj](https://github.com/user-attachments/assets/e0cbd764-a08c-4d85-bd8b-9602580f6263)
![kjhfqojhruiq](https://github.com/user-attachments/assets/594d8e34-7c1a-4d5f-9b6a-aec9c40163b8)
![kajshiuyih](https://github.com/user-attachments/assets/32595d15-127e-4257-b54e-c983a4493e39)
![akweujbsfk](https://github.com/user-attachments/assets/877587f1-2e14-4f80-9560-a054774f4b15)

**Environment**

- Ghostfolio Version 2.124.1 
- Self-hosted (docker)
- Experimental Features disabled
- Browser Firefox
- OS Windows

**Comment by dtslvr** [comment] 2024-11-30 18:31
Hi @BloodBlender

Thank you for the report. Can you please attach a minimal export file to reproduce this scenario?

**Comment by BloodBlender** [comment] 2024-11-30 18:50
Sure 
[ghostfolio-export-202411301949.json](https://github.com/user-attachments/files/17966464/ghostfolio-export-202411301949.json)

**Comment by karter16** [comment] 2024-12-04 05:02
Be prepared for this bug report to go absolutely nowhere. For some reason there appears to be zero priority given to fixing the fundamental flaws in Ghostfolio's calculations.

**Comment by dtslvr** [comment] 2024-12-04 19:06
> Sure [ghostfolio-export-202411301949.json](https://github.com/user-attachments/files/17966464/ghostfolio-export-202411301949.json)

Thank you for providing the export file, @BloodBlender! I have imported and analyzed it, but I'm having trouble understanding the issue.

<img width="1148" alt="portfolio-evolution" src="https://github.com/user-attachments/assets/21c43cba-73a1-4d16-b02c-d48436eedd83">

<img width="1148" alt="investment-timeline" src="https://github.com/user-attachments/assets/343b2c90-6d6c-440f-acd1-651d9f62b634">

Could you elaborate further?

**Comment by dtslvr** [comment] 2024-12-04 19:53
Thanks for the update! It might have been due to missing exchange rates. For future issues, checking the logs could help identify the cause.

I will close this for now. Feel free to open a new issue if the scenario is reproducible.

**Closed by dtslvr** 2024-12-04 19:53 UTC
Labels: question
