### ISSUE TITLE
[BUG] Fix eslint configuration

### ISSUE THREAD

**Issue by dtslvr** [ghostfolio/ghostfolio#2782] opened 2023-12-25 09:41 UTC
Running `npm run lint` exits with the following error:

Linting "api"...

 >  NX   ESLint configuration in apps/api/.eslintrc.json » ../../.eslintrc.json is invalid:

        - Property "extends" is the wrong type (expected string but got `[null,"plugin:storybook/recommended"]`).
        - Property "extends[0]" is the wrong type (expected string but got `null`).
        - "extends" should match exactly one schema in oneOf. Value: [null,"plugin:storybook/recommended"].
   
   Referenced from: /home/fares/repo/_projects/ghostfolio/apps/api/.eslintrc.json
   Pass --verbose to see the stacktrace.

 >  NX   Ran target lint for project api (613ms)
 
    ✖    1/1 failed
    ✔    0/1 succeeded [0 read from cache]
 
   View structured, searchable error logs at https://nx.app/runs/SDeoEU7RfZ

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

_Originally posted by @underwater in https://github.com/ghostfolio/ghostfolio/discussions/2772#discussioncomment-7937304_

**Comment by underwater** [comment] 2023-12-25 18:09
@dtslvr you can assign it to me, and I will dig into this right after we close the p/r on permissions

**Comment by underwater** [comment] 2023-12-27 08:18
@dtslvr 
I suspect, updating the .eslintrc.json file to use
`  "extends": ["plugin:storybook/recommended"]`
instead of 
` "extends": [null, "plugin:storybook/recommended"]`

would likely resolve the` .eslintrc.json is invalid error` but the linting itself would raise a large number of errors / warnings (mostly relating to` circular dependencies` and suggestions for` using relative paths for internal imports`.....

I did rollback locally to various older commit points to check last occurence when linting worked, but it seems linting always generated errors.... Is the script `yarn lint` being actively used during local development or triggered in CI / CD ?

**Comment by dtslvr** [comment] 2023-12-28 08:53
Linting has not been used at this point, but I think it would be an improvement. To get to this point, I suggest that we resolve the circular dependencies and temporarily deactivate the rule with the relative paths imports.

> "extends": ["plugin:storybook/recommended"]

Good discovery! Can you create a PR for this change?

**Comment by underwater** [comment] 2023-12-28 15:22
Yes, sure, I return in a few days, and will have a look - B wishes for end
of year holidays ;-)

**Comment by underwater** [comment] 2024-01-08 13:50
@dtslvr I am sorry but again due to health will be offline for another 10 days, and suggest perhaps un-assign me this issue, for better visibility,.....

**Comment by dtslvr** [comment] 2024-01-10 20:08
@underwater No problem. Get well soon!

**Comment by dw-0** [comment] 2024-09-28 16:57
@dtslvr I stumbled across this issue just a moment ago while setting up the dev environment. You can assign this issue to me if you like and i can have a look. I saw, that removing "null" like mentioned above results in a lot of different eslint issues. My preferred approach would be to:
1. fix little eslint rule breaches that don't involve multi line refactoring
2. switch elsint rules which would require refactoring over multiple lines to warnings, so that those warnings can be handled later and the PR won't get too large / affects too many changed lines at once

**Comment by dw-0** [comment] 2024-09-29 14:16
Hey @dtslvr, while working on this issue, i stumble across several unused methods, interfaces, types and parameters. Some of them causing eslint errors. Im wondering what your take on handling those would be? Ignore for now and don't handle it within the scope of this ticket, or remove those unused parts of the code?

**Comment by dtslvr** [comment] 2024-09-29 16:17
My preferred procedure would be to make it work first. Then, in a follow up task, narrow the rules. It would be great to spot unused imports / methods.

Step by step 🙂

**Comment by dw-0** [comment] 2024-09-30 20:17
So, i managed to get all errors as warnings, so they can be resolved later and i added a lint command to the existing pre-commit git hook file.

I was wondering if husky should be added to the project for handling the pre-commit hook. Since there are no github actions set up which lint a PR, there is actually no failsafe for PRs containing lint errors.

In DEVELOPMENT.md i saw, that git hooks should be added manually to the projects git config. I would assume this is an easy to miss/ignore step (tbh, i didn't do it myself at first - "ahhh, i'll just do it later"). With a husky pre-commit, there would be no requirement for manually setting up git hooks anymore, they are "just there" already.

What is your opinion to this @dtslvr ?


On a side note:
I don't understand the behavior of the current pre-commit file. For me it looks like it does not work as intended.
I attached a short video, which shows what the pre-commit hook actually does. For the test, i disabled running prettier on save, so that i explicitly commit something that is not formatted correctly:

https://github.com/user-attachments/assets/76d3476f-1957-441f-b496-5daaaef554f4

The following steps can be observed:
1. Explicitly format lines of code incorrectly
2. Commit the file
3. Watch the pre-commit hook get fired (we can actually see that the lint command is incorrect still, it only lints the api project for some reason, will fix that)
4. A fatal `fatal: pathspec '>' did not match any files` is thrown

Now the odd things start:
What actually happened is, that the incorrectly formatted file got committed, after that the file got formatted, thats why we can see the changed lines (blue indicator in the editor gutter). When looking at the git diff of the "should reformat" commit, we can see that the incorrectly formatted code indeed was committed.

I am unsure why this happend. My current suggestion would be to run a format:check instead as this will actually reject the committing of the file:
![image](https://github.com/user-attachments/assets/2f5368db-3e99-4109-af86-83bee313300b)
Since there is no error handling in the pre-commit script (and i assume it gets quite complex), it might be simpler to do it that way. Though, i understand why it probably was set up the way it is, to only check the currently staged and therefore modified files. But it seems to not work correctly and this approach is error prone.

**Comment by dtslvr** [comment] 2024-10-01 15:25
Thanks for your input on the pre-commit hook and linting setup. I don’t have a strong opinion about husky. It still seems to be widely used, and it could simplify the hook management. However, I suggest we prioritize fixing the ESLint errors first to improve code quality.

As for the current pre-commit behavior, switching to `format:check` seems wise to prevent incorrectly formatted files from being committed. Let's address the linting issues and revisit the pre-commit hook improvements later. Okay?

**Comment by dw-0** [comment] 2024-10-01 15:51
Sounds good to me! I will provide a PR later this evening.

**Closed** 2024-10-03 18:39 UTC
Labels: bug, help wanted, hacktoberfest

**Comment by dtslvr** [comment] 2024-10-03 18:41
@dw-0 Now that this is done, what next step do you suggest?

**Comment by dw-0** [comment] 2024-10-03 19:34
@dtslvr There are several improvements we could make.
I think the next logical step would be to integrate husky and a pre-commit hook for linting and a prettier check. That way no manual setup for the existing hook is necessary for new contributors. Also, it will fix the current unintended behavior of the current hook.

Then we could try and get rid of all the unused code mentioned earlier. It might make sense to work on that as some unused code might break eslint rules once we enable them again. That way, the offending code is already gone and the codebase already a bit cleaner.

After that we could think about switching easy to fix rules back from "warn" to "error" one by one. This may involve larger refactorings, some with probably little code changes but many touched files and others with actual changes to the code and logic.

We could also think about adding the recommended sets of typescript-eslint (and overwrite every rule to "warn" until its fixed) before we start switching the previous rules back to error again. There might be some overlapping rules which may clean up the projects eslintrc.json once all rules are correctly in place again: 
* https://github.com/typescript-eslint/typescript-eslint/blob/main/packages/eslint-plugin/src/configs/recommended-type-checked.ts 
* https://github.com/typescript-eslint/typescript-eslint/blob/main/packages/eslint-plugin/src/configs/stylistic-type-checked.ts 
* (or, alternatively to the stylistic-type-checked ruleset because they are deprecated and won't receive updates anymore, pick https://eslint.style/guide/why instead)

And after all of the previous actions: resolve the circular dependency issue. This will probably involve the largest, structural refactorings to the whole codebase.

What are your thoughts?

**Comment by dtslvr** [comment] 2024-10-04 06:41
Thanks for this outline, @dw-0. I have created a first issue: https://github.com/ghostfolio/ghostfolio/issues/3866

**Comment by dtslvr** [comment] 2024-10-05 11:09
> while working on this issue, i stumble across several unused methods, interfaces, types and parameters

@dw-0 Which rules need to be activated to address these issues? That would be the next step I guess.

**Comment by dtslvr** [comment] 2024-10-05 12:02
> Or we could actually think about enabling the recommended-type-checked rules i mentioned and start from there.

Okay, I have created an issue for that: https://github.com/ghostfolio/ghostfolio/issues/3874
